version: "3.8"
services:
  backend:
    build: ./backend # or use 'image: your-backend-image' if using a prebuilt image
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
      MYSQL_DATABASE: foodpanda
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
    networks:
      - app-network
   

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: foodpanda
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    

volumes:
  mysql-data:
  
networks:
  app-network:
